### ISSUE TITLE
[Feature Request] Use source maps for better stack traces in WF isolate code

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#101]
**Is your feature request related to a problem? Please describe.**

Workflow stack traces show the compiled JS as sources instead of the TypeScript sources, this makes WF code hard to debug.

**Describe the solution you'd like**

Stack traces should include the source code the way they do in [ts-node](https://www.npmjs.com/package/ts-node).

**Additional context**

Currently we build the Workflow Isolate using Webpack from compiled JS files (`./lib`) instead of the TypeScript source (`./src`), this might need to change in order to provide proper sourcemaps.

**Comment by lorensr** [comment]
Is it possible to get workflow error stack traces with `src/*.ts` line numbers? I'm seeing `lib/*.js` in worker output:

@temporalio/test: 2022-03-02T01:47:43.406Z [WARN] [temporal_sdk_core::worker] Failing workflow activation run_id="453a299c-2334-4e7b-b581-8c3bbd216eac" failure=Failure { failure: Some(Failure { message: "Failed to convert value: str1", source: "TypeScriptSDK", stack_trace: "PayloadConverterError: Failed to convert value: str1\n    at toPayload (webpack-internal:///../common/lib/converter/payload-converter.js:60:15)\n    at eval (webpack-internal:///../common/lib/converter/payload-converter.js:78:34)\n    at Array.map (<anonymous>)\n    at toPayloads (webpack-internal:///../common/lib/converter/payload-converter.js:78:19)\n    at eval (webpack-internal:///../workflow/lib/workflow.js:118:52)\n    at new Promise (<anonymous>)\n    at scheduleActivityNextHandler (webpack-internal:///../workflow/lib/workflow.js:91:12)\n    at scheduleActivity (webpack-internal:///../workflow/lib/workflow.js:142:12)\n    at eval (webpack-internal:///../workflow/lib/workflow.js:314:24)\n    at twoStringsActivity (webpack-internal:///./lib/workflows/two-strings.js:13:26)", cause: None, failure_info: None }) }

**Comment by bergundy** [comment]
You should get the sourcemaps if you use ts-node, I think there's another way though, I'd need to check.
