### ISSUE TITLE
[Feature Request] Searchable SDK docs

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-node#115]
**Is your feature request related to a problem? Please describe.**

hard to find things in the SDK docs, search would be nice!

**Describe the solution you'd like**

lets see if there's ways to do this without algolia so that we dont rely too much on them, but if we have to then its ok.

**Comment by lorensr** [comment]
might also be nice if searching in the docs.temporal.io search box sourced SDK results

**Comment by bergundy** [comment]
@lorensr interesting but I'd leave that for future work.
