### ISSUE TITLE
[Feature Request] Auto compile project on worker run

### ISSUE THREAD

**Issue by rylandg** [temporalio/sdk-node#116]
Right now it's expected for the user to maintain a terminal process that watches a directory and invokes the TypeScript compiler on any recognized change. Separately, when they want to run their workflow they are expected to start a worker. This worker needs to be restarted on any change to the workflow or activity code.

It would be great if running a worker did the compilation too. That way I could only run the worker in some cases.

**Comment by bergundy** [comment]
That's a great idea, would definitely simplify the local development environment by a lot.
I was already thinking we'd compile Workflow typescript code as part of the webpack step in-worker for improving the generated source maps.

We should get back to this as soon as the outstanding proposals are implemented.
