### ISSUE TITLE
[Bug] No message returned when running hello world sample app

### ISSUE THREAD

**Issue by denjalonso** [temporalio/sdk-node#127]
**Describe the bug**
No message returned when i start the Workflow, running getting started (hello world sample app), step 3 "Run your Workflow".

**To Reproduce**
1. Go to https://docs.temporal.io/docs/node/getting-started/
2. Follow steps
3. Then when running `node lib/worker/schedule-workflow.js` it not returns "Hello, Temporal!" message:
````
$ node lib/worker/schedule-workflow.js

````
**Expected behavior**
Starts the scheduled workflow

**Screenshots/Terminal ouput**
<img width="880" alt="Screenshot 2021-06-17 at 16 53 14" src="https://user-images.githubusercontent.com/3237551/122431767-a83eef80-cf8c-11eb-988d-80f13b850562.png">

Temporal web after start (state is running):
<img width="2544" alt="Screenshot 2021-06-17 at 16 55 30" src="https://user-images.githubusercontent.com/3237551/122432127-f7852000-cf8c-11eb-88fa-6f494d807114.png">

Workflow detail in temporal web (state is running):
<img width="2553" alt="Screenshot 2021-06-17 at 16 56 58" src="https://user-images.githubusercontent.com/3237551/122432344-256a6480-cf8d-11eb-8ac5-2ab4028b237a.png">

**Versions (please complete the following information where relevant):**
 - OS: macOs Big Sur 11.4 Apple M1
 - Node v16.3.0 (tj/n)
 - `"temporalio": "0.2.2"`
 - Temporal server with docker compose

**Additional context**
I have tried with different versions of node.

**Comment by denjalonso** [comment]
This is the log output in the server (temporal):

```
Jun 17 16:53:05.003  WARNtemporal_sdk_core::workflow_tasks: Attempted to complete activation for nonexistent run, run_id: ""
    in temporal_sdk_core::complete_workflow_task with completion=WfActivationCompletion(run_id: , status: Success( ScheduleActivity ))
```

**Comment by zomble** [comment]
I see that same issue.

```
const activation = coresdk.workflow_activation.WFActivation.decode(new Uint8Array(buffer));
```

Is producing:

```
WFActivation {
  jobs: [ WFActivationJob { startWorkflow: [StartWorkflow] } ],
  taskToken: Uint8Array(36) [
    55, 52, 55, 53, 100, 53, 102,  53,  45,
    49, 50, 57, 98,  45, 52,  50,  98, 100,
    45, 98, 55, 51,  99, 45, 100, 102,  99,
    52, 49, 50, 57,  49, 51, 100,  97,  57
  ],
  timestamp: Timestamp {
    seconds: Long { low: 1624001582, high: 0, unsigned: false },
    nanos: 535530575
  }
}
```

**Comment by bergundy** [comment]
Thanks for the detailed report.
Looks like we published a version with a mismatch in the proto definitions between core and the worker.
I'll make sure to publish a new version ASAP.
We have an open issue to automate the release process which should eliminate these sort of bugs.

**Comment by bergundy** [comment]
I just noticed that since the proto library contains generated code it doesn't automatically get published.
Working on a fix for that.

**Comment by bergundy** [comment]
Once CI passes for #128 I'll republish the packages.

**Comment by bergundy** [comment]
AFK, will publish as soon as I'm back online.

**Comment by denjalonso** [comment]
Thx

**Comment by bergundy** [comment]
Just published

**Comment by bergundy** [comment]
`temporalio@0.2.4` with `@temporalio/proto@0.2.2`
