### ISSUE TITLE
[Feature Request] Discuss activity registration and imports

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#168]
Currently we use the following to import Activity functions as stubs in a Workflow.
```ts
import { myActivity } from '@activities/something';
// NOTE: `../activities` is not supported but that can be fixed
```

This is pretty convenient since provides implicit type safety

Another approach would be to use something like `ExternalDependencies`
`workflows/example.ts`
```ts
const { myActivity } = Context.activities<ActivityInterface>();
```
`worker/index.ts`
```ts
import * as activities from '../activities';
const worker = await Worker.create<{ activities: ActivityInterface }>({ activities });
```

Here we rely on an interface definition for type safety but it allows more flexibility in registration and it seems like there's less "magic" going on.

One other option that comes to mind is to have a single `@activities` file (e.g. `src/activities/index.ts` and disallow imports from `@activities/something`, this way we'd have unique activity registration without worrying about duplicates.

**Comment by joebowbeer** [comment]
The `@activities` idiom still strikes me as odd. I interpret this as a scoped import, declared as a dependency in package.json. I'd prefer if this were changed to something unambiguous and preferably explicit.

I'm also not keen about the automatic imports from the working directory. This seems concise and convenient for starter apps, but I want to see a more verbose and flexible layer provided for advanced users. Ideally, the simple style would be built on the complex layer.

**Comment by bergundy** [comment]
@joebowbeer I agree, this will change in the very near future.
