### ISSUE TITLE
[Feature Request] Discuss project structure

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#169]
From the Temporal community slack channel:

Now that we bundle Workflow code with Webpack we can have Typescript output a commonjs module instead of ES module.
This opens the door to simplifying the project structure, instead of 4 tsconfig files we can now have a single config file.
Doing this means sacrificing some type safety, for example, node types, WeakMap and WeakRef are not defined in the Workflow tsconfig file which should help newcomers avoid some easy to make mistakes.

Specifically these customizations have been made to the workflows `tsconfig.json`
```
      "lib": [
        "es5",
        "es2015.core",
        "es2015.generator",
        "es2015.iterable",
        "es2015.promise",
        "es2015.proxy",
        "es2015.reflect",
        "es2015.symbol",
        "es2015.symbol.wellknown",
        "es2016.array.include",
        "es2017.object",
        "es2017.intl",
        "es2017.sharedmemory",
        "es2017.string",
        "es2017.typedarrays"
      ],
      "typeRoots": [
        "."
      ],
```
(`Weak*` types and node types omitted)

When modifying the project to use a single TS config file, some noticeable differences are:
1.
```
import fs from 'fs';
```
In the composite project you get an error:
Cannot find module 'fs' or its corresponding type declarations
Not a compile time error in the modified project.

2.
```
new WeakMap();
```
In the composite project you get this error:
```
'WeakMap' only refers to a type, but is being used as a value here. Do you need to change your target library? Try changing the `lib` compiler option to es2015 or later.
```
No compile time error in the modified project.

When trying to use fs in the modified example the worker fails to start with:
```
2021-05-20T07:09:18.493Z [INFO]           using description file: /private/tmp/example/package.json (relative path: ./node_modules/fs)
2021-05-20T07:09:18.493Z [INFO]             no extension
2021-05-20T07:09:18.493Z [INFO]               Field 'browser' doesn't contain a valid alias configuration
2021-05-20T07:09:18.493Z [INFO]               /private/tmp/example/node_modules/fs doesn't exist
When instantiating a new WeakMap the user will get an error on Worker startup:
Error [DeterminismViolationError]: WeakMap cannot be used in workflows because v8 GC is non-deterministic
```

**Comment by bergundy** [comment]
https://temporalio.slack.com/archives/C01DKSMU94L/p1621337921005400

**Comment by sw-yx** [comment]
better developer experience for slightly weaker type safety sounds fine to me. lets make an effort to have nice errors when people do stuff they are not supposed to do

**Comment by bergundy** [comment]
As discussed, let's drop the complex project structure.
We should update our samples and documentation accordingly.
