### ISSUE TITLE
[strawman] React-like API proposal

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-node#181]
just sketching out what a React-like API might look like. it might help solve some of our API design challenges (by starting from something already proven) and our adoption might be helped GREATLY since most JS people know React.

where we depart from React: 
- React doesn't model Sagas
- React doesn't need hook registration in advance
- React doesn't allow external invocations.

other design considerations: 
- flexible file and folder structure as much as possible.
- type safety without poor JS dev experience

## Workflows and Activities

```tsx
import { Activity, Workflow } from 'fakeTemporal'

export const activities = {
	async chargeStripe(amount) {
		res = await call('/charge', amount)
		return res // todo: handle err case
	}
	async reverseCharge(id) {
		res = await call('/reverse', id)
		return res // todo: handle err case
	}
	async function chargeStripe(amount) {
		res = await call('/charge', amount)
		return res // todo: handle err case
	}
} 


type ValidStatuses = 'EMAIL' | 'COMPLETE' | 'CANCELED'
const invoke = (activity, ...args) = {
	// convenience function; users can call Activity.create directly if they need to customize/override these
	return Activity.create({
				activity, 
				options: {
					startToCloseTimeout: 1000 // this is the default if options not specified
				}
			})(...args)
}
export class MyWorkflow extends Workflow <WFInterface> {
	status: ValidStatuses = 'EMAIL' // all non private variables are queryable
	activities = activities // a workflow registers its own activities by convenience
	signals = {
		cancelTransaction() {
			if (status === 'COMPLETE') {
				return 'Transaction already completed, cannnot be canceled"
			} else {
				status = 'CANCELED'
			}
		}
	}
	async execute(amount) {
		const transactionId = invoke(activities.chargeStripe, amount)
		sleep(3000) // wait for cancel
		if (status === 'CANCELED') {
			await invoke(activities.reverseCharge, amount)
			status = 'COMPLETE'
		} else {
			await invoke(activities.emailUser, transactionId)
		}
	}
}

// usage
import { Client } from 'fakeTemporal'

const client = new Client({ 
	register: MyWorkflow, // register both WF and associated activity
	taskQueue: 'my-workflow' // defaults to `node-workflow`
})
client.execute(amount)
console.log(client.query.status) // 'EMAIL'
client.signal.cancelTransaction() // cancel
console.log(client.query.status) // 'CANCEL'
```

## Infinite Workflows

Infinite Workflows have no `execute`, they are always live and `continueAsNew` under the hood. We might also call them `Entity`s

```tsx
import { Activity, InfiniteWorkflow } from 'fakeTemporal'

// as above
export class MyWorkflow extends InfiniteWorkflow <WFInterface> {
	status: ValidStatuses = 'WAITING'
	activities = activities // a workflow registers its own activities by convenience
	signals = {
		cancelTransaction() {
			status = 'CANCELED'
		}
		startTransaction() {
			const transactionId = invoke(activities.chargeStripe, amount)
			sleep(3000) // wait for cancel
			if (status === 'CANCELED') {
				await invoke(activities.reverseCharge, amount)
				status = 'WAITING'
			} else {
				await invoke(activities.emailUser, transactionId)
			}		
		}
	}
}

// usage
import { Client } from 'fakeTemporal'

const client = new Client({ 
	register: MyWorkflow, // register both WF and associated activity
})
client.signal.startTransaction() // started
console.log(client.query.status) // 'WAITING'
client.signal.cancelTransaction() // canceled
console.log(client.query.status) // 'CANCELED'
```

**Comment by sw-yx** [comment]
i'm not done yet thinking thru this, just sketching it out in public.

**Comment by bergundy** [comment]
Yes, this is the direction I was going too.
Using a class for workflows, I still like the anonymous class (`{ main, ... }`) option but the downside of it is that it doesn't have a reference-able name like a class, this might solve the workflow client issue where you need to give the filename and the type: `client.stub<WFInterface>('filename')`, this can turn into `client.stub(MyWorkflow)` as you suggested.

I thought about renaming `main` to `execute` too, it aligns with the workflow stub method.

Some issues that I see with this sketch:
- Workflows and activities can't live in the same file because workflows can't import everything activities can
  - This may be solvable by adding some boundaries to where activities and workflows are in the file sort of like svelte's tags
- The are to problems with the `invoke` function:
  1. There's no way to pass in activity options
  2. What would be the equivalent of `invoke` for child workflows?
 
I like this instead of invoke:
```ts
const { myActivity } = Context.activities({ taskQueue: 'q' });
await myActivity(...argsWithTypeHints);  // Typescript only :(
```

Making `invoke` return a Promise is very important too because users can use familiar `async / await` and `Promise.{all,catch}` syntax.

I have managed to flatten the signals and queries and still keep the implementation type safe.

It still requires you to define signals nested in the interface though:
```ts
export interface MyInterface extends WorkflowInterface {
  execute(x: number): Promise<void>;
  signals: {
    incr(i: number): void;
  };
}

export class MyWorkflow implements Workflow<MyInterface> {
  incrSignal(i: number): Promise<void> {
    // ...
  }
  execute(x: number): Promise<void> {
    // ...
  }
}
```

This can be achieved with template literals in TS:
```ts
export type Signals<S extends WorkflowInterface['signals']> = S extends Record<string, WorkflowSignalType>
  ? {
      [P in keyof S as `${string & P}Signal`]: (...args: Parameters<S[P]>) => ReturnType<S[P]>;
    }
  : {};

export type Workflow<W extends WorkflowInterface> = Signals<W['signals']> & {
  execute(...args: Parameters<W['execute']>): ReturnType<W['execute']>;
};
```

**Comment by bergundy** [comment]
A direct implementation of the current workflow interface with a class would look like:
```ts
export class MyAlternative implements MyInterface {
  value = 0;

  async execute(x: number): Promise<void> {
    this.value = x;
    await CancellationScope.current().cancelRequested;
  }

  signals = {
    incr: (i: number): void => { // bind this to the MyAlternative instance
      this.value += i;
    },
  };
}
```

**Comment by bergundy** [comment]
As for infinite workflows I've given some thought to that too, we all have... :)
The biggest problem is that you can't insure that there'll be an opportunity to continue as new, for example here:
```ts
export class InfiniteExample implements extends InfiniteWorkflow<SomeInterface> {
  signals = {
    preventContinueAsNew: async (): Promise<void> => {
      for (;;) {
        await sleep(1000);
      }
    },
  };
}
```

**Comment by bergundy** [comment]
Another option that comes to mind is having named factory function.
This approach allows more flexibility because it allows customization of the workflow based on given arguments. It has already been requested by someone on the community slack.
Another advantage here is that initialization is done when workflow starts, so there's no need to pre-initialize variables like `value` as shown in the example above.

```ts
// makeWorkflow receives execute args
export function myWorkflow(initialValue: number) {
  let value = initialValue;

  async function execute(): Promise<void> {
    await CancellationScope.current().cancelRequested;
  }
  const signals = {
    incr(i: number): void {
      value += i;
    },
  };
  const queries = {
    value(): number {
      return value;
    },
  };

  return {
    execute,
    signals,
    queries,
  };
  // alternatively return the MyAlternative from the sample above
  // but change the initial value value to be provided in the constructor instead of the execute function.
}
```

**Comment by bergundy** [comment]
We could use the function name for registration (export them all from `index.ts`?)

Using registration we can remove the need to specify both type and filename to create a workflow stub:
```
// workflows/index.ts
export function workflowA() { ... }
export function workflowB() { ... }

// express-app/start-a-workflow.ts
import { workflowA } from '../workflows';
const client = new WorkflowStub(workflowA);
```

**Comment by sw-yx** [comment]
> Workflows and activities can't live in the same file because workflows can't import everything activities can

i am ok with this for the convenience. can use hooks style linting but honestly i dont really think we need it, people understand that different rules apply for different thigns

> The are to problems with the invoke function: There's no way to pass in activity options

you can, the `invoke` function is a thin wrapper for `Activity.create` (made up API), you can change whatever you want

> What would be the equivalent of invoke for child workflows?

`Workflow.StartChild`?

> The biggest problem is that you can't insure that there'll be an opportunity to continue as new, for example here

bad code will always be possible and we shouldnt try to solve the halting problem :shrug:

> Another option that comes to mind is having named factory function.

You can also customize workflows in constructor or with public class fields. but i dont really mind this is close enough to classes that its not that different

**Comment by bergundy** [comment]
> > Workflows and activities can't live in the same file because workflows can't import everything activities can
> 
> i am ok with this for the convenience. can use hooks style linting but honestly i dont really think we need it, people understand that different rules apply for different thigns

What are you saying, that there's a way to put workflows and activities in the same file?

> > The are to problems with the invoke function: There's no way to pass in activity options
> 
> you can, the `invoke` function is a thin wrapper for `Activity.create` (made up API), you can change whatever you want

Then why do you even need invoke, if create can just return a callable?

> > What would be the equivalent of invoke for child workflows?
> 
> `Workflow.StartChild`?

Wouldn't that imply that invoke should be called startActivity or something similar?
 
> > The biggest problem is that you can't insure that there'll be an opportunity to continue as new, for example here
> 
> bad code will always be possible and we shouldnt try to solve the halting problem 🤷

I'd rather come up with a solution that does not allow users to write WFs that can get stuck, there are other scenarios which can prevent a WF from continuing as new, some not as obvious.

> > Another option that comes to mind is having named factory function.
> 
> You can also customize workflows in constructor or with public class fields. but i dont really mind this is close enough to classes that its not that different

It's very similar but more flexible.

**Comment by sw-yx** [comment]
we discussed this offline - Roey will explore ways to organize WF+Activities as a single file (so we closely model React components and hooks/lifecycle methods) and/or look at multiple workflow directories so we can organize activities and workflows in logical biz logic units

**Comment by sw-yx** [comment]
```ts
// makeWorkflow receives execute args
export function myWorkflow(initialValue: number) {
  let value = initialValue;

  return {
    execute(): Promise<void> {
      await CancellationScope.current().cancelRequested;
    },
    signals: {
      incr(i: number): void {
        value += i;
      },
    },
    queries: {
      value(): number {
        return value;
      },
    },
  };
}
```

**Comment by bergundy** [comment]
We can't continue as new after every signal, there might be running activities / timers / child workflows.
The only time you can auto continue as new is when there aren't any pending completions in the workflow.
Even that's not completely safe, but we may be able to make it "safe enough" by constraining the API.

**Comment by bergundy** [comment]
We also agreed to flatten the `Context` object into the `@temporalio/workflow` package.

**Comment by bergundy** [comment]
Tried to get our proposal working and it ran into a TS limitation where type safety for `execute` args requires our users to do some extra work.

First of all if we define the workflow interface as follows:
```ts
export interface MyWorkflow extends WorkflowInterface {
  execute(a: number, b: string): Promise<string>;
}
```

If we want to implement a factory for it we need a `WorkflowFactory` generic type to validate the factory args:

```ts
export const myWorkflow: WorkflowFactory<MyWorkflow> = (a: number, b: string) => {
  return {
    async execute(): Promise<string> {
      return 'hey';
    },
  };
}
```

Or with a `function`:

```ts
export const myWorkflow: WorkflowFactory<MyWorkflow> = function(a: number, b: string) {
  return {
    async execute(): Promise<string> {
      return 'hey';
    },
  };
}
``` 

With classes this is impossible to validate in one go and requires 2 additional types, `WorkflowImpl` and `WorkflowConstructor`:

```ts
// "implements" here is redundant because `WorkflowConstructor<T>` validates this below.
class MyWorkflowImpl implements WorkflowImpl<MyWorkflow> {
  // implements WorkflowImpl<MyWorkflow> does not type check the constructor
  constructor(protected a: number, protected b: string) {}

  async execute(): Promise<string> {
    return 'wow';
  }

  signals = {
    async quit() {},
  };
}

const myWorkflow: WorkflowConstructor<MyWorkflow> = MyWorkflowImpl;

// Or with a factory

const myWorkflow: WorkflowFactory<MyWorkflow> = (...args) => new MyWorkflowImpl(...args);
```

It might not be the end of the world, just a minor inconvenience.

@sw-yx WDYT?

**Comment by sw-yx** [comment]
i think its ok too. function style still seems best. realistically i'm not really going to implement `WorkflowFactory<>` in my code, i'm just going to expect TypeScript to ducktype validate at the callsite.

**Comment by joebowbeer** [comment]
I estimate that 60% of Typescript programmers are familiar with React. That's a large number, but still leaves a substantial number who aren't. Therefore I caution against overestimating the cognitive resonance achieved from a React API. (Which is not to say that this isn't a good idea on its own merits.)
