### ISSUE TITLE
[Feature Request] Sort docs menu items

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-node#195]
My impulse is to scroll looking for a particular thing, and then I realize it's not in alphabetical order, so I `Cmd-F`.

![image](https://user-images.githubusercontent.com/251288/130338440-7399c5fa-05a5-40ca-9576-2ace9e3d2875.png)

**Comment by bergundy** [comment]
Yeah, we might just want to not output any of the generated protobuf type defs in the API reference.
