### ISSUE TITLE
[Feature Request] Clarify namespace version menu items

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-node#196]
The repeated `v1`s in the image below appears at first like a bug. It might help if the menu items were:

```
command
command.v1
common
common.v1
```

Or since `command` and `common` pages are so little, combining to:

```
command.v1
common.v1
```

![image](https://user-images.githubusercontent.com/251288/130338526-b77bcc86-e016-43c1-80fa-e5fc83f19e2d.png)

**Comment by bergundy** [comment]
Same as the previous issue, we might just want to omit the generated protobuf types from the API reference.
Let's consider our options.
Also related is #115
