### ISSUE TITLE
[Feature Request] Provide a method for getting a client instance on `activity.Context`

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-node#214]
### Is your feature request related to a problem? Please describe.

Currently there's no easy way to get the *same* client that the worker/workflows use from inside an activity. This surfaced as a problem where worker was using the right URL for the server, but an activity sending a signal was not.

### Describe the solution you'd like

In title

**Comment by bergundy** [comment]
Apparently this isn't required because we can just pass class instances as activities.
I'm submitting a PR that makes this simpler and adds snippets for the docs.

**Comment by bergundy** [comment]
This is already supported as demonstrated here: https://github.com/temporalio/samples-node/pull/18

I'll add to the docs.
