### ISSUE TITLE
[Feature Request] Improve Context API docs

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-node#229]
Could this show up as `Context` instead of `ContextImpl`, so it's easier to find?

![image](https://user-images.githubusercontent.com/251288/132553046-2116ee5c-6989-42e7-8b54-11828530bc6f.png)

And can it list default activity options either here:

https://nodejs.temporal.io/api/classes/workflow.ContextImpl#configureactivities

or here:

https://nodejs.temporal.io/api/namespaces/worker#activityoptions

**Comment by bergundy** [comment]
This goes away in #225, your input on it is more than welcome
