### ISSUE TITLE
[Feature Request] Document external calling convention for activities

### ISSUE THREAD

**Issue by Sushisource** [temporalio/sdk-node#232]
### Is your feature request related to a problem? Please describe.

When we changed activity registration the way activities are called from outside of the SDK was broken/different. How that works should be documented and we should maintain compatibility going forward.

### Describe the solution you'd like

* Document how calling activities by type-string works
* When the worker fails to find a matching activity type for a given activity task, it should report what activities are available in the error message so user can see that in workflow history

### Additional context

See https://temporalio.slack.com/archives/C01DKSMU94L/p1631223937036500

**Comment by bergundy** [comment]
> ### Is your feature request related to a problem? Please describe.
> When we changed activity registration the way activities are called from outside of the SDK was broken/different. How that works should be documented and we should maintain compatibility going forward.
Yes, that's why I changed it before beta so we'd be forwards compatible and consistent with the other SDKs.
> 
> ### Describe the solution you'd like
> * Document how calling activities by type-string works
https://nodejs.temporal.io/api/classes/workflow.ContextImpl#configureactivities
> * When the worker fails to find a matching activity type for a given activity task, it should report what activities are available in the error message so user can see that in workflow history
Sounds good, it should be easy to add that.

To summarize, we should add the list of available activities to the "activity not found" error.

**Comment by sw-yx** [comment]
@bergundy did we document this though?

**Comment by bergundy** [comment]
@sw-yx it's documented here: https://nodejs.temporal.io/api/namespaces/workflow#createactivityhandle
