### ISSUE TITLE
[Feature Request] continueAsNew with a taskQueue

### ISSUE THREAD

**Issue by alex-dixon** [temporalio/sdk-node#266]
### Describe the solution you'd like

I'm looking for a way to continue a workflow as a new workflow but on a different task queue than the workflow started on.

If there's a way to do this with the current API I just don't know what it is. It seems continue as new performs this functionality but does not currently allow specifying a task queue.

**Comment by lorensr** [comment]
Here's the version of the function that takes options: https://nodejs.temporal.io/api/namespaces/workflow#makecontinueasnewfunc

I'm not finding the definition of `ContinueAsNewOptions` though.

**Comment by Sushisource** [comment]
`ContinueAsNewOptions` already does in fact allow setting a task queue, so this should work already.

We'll need to make sure it shows up in the docs properly.

@alex-dixon Try using the function @lorensr posted and set the task queue in the passed in options.

**Comment by sw-yx** [comment]
@bergundy for some reason `ContinueAsNewOptions` are not exposed at all in  `https://nodejs.temporal.io/api/namespaces/workflow/#makecontinueasnewfunc`

**Comment by bergundy** [comment]
Probably forgot to export it, I'll take care of it
