### ISSUE TITLE
[Feature Request] Return Promise from Worker.shutdown()

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-node#284]
### Describe the solution you'd like

Currently `shutdown` returns `void`:

https://nodejs.temporal.io/api/classes/worker.Worker#shutdown

I think it would be nice if it returns a `Promise<void>` that resolves when the Worker finishes shutting down.

### Additional context

It would change this:

```js
  let runPromise = null;
  let worker = null;

  before(async function() {
    worker = ...  
    runPromise = worker.run();
  });

  after(async function() {
    worker.shutdown();
    await runPromise;
  });
```

to:

```js
  let worker = null;

  before(async function() {
    worker = ...
    worker.run();
  });

  after(async function() {
    await worker.shutdown();
  });
```

**Comment by bergundy** [comment]
To clarify catching is for avoiding unhandled rejection.

**Comment by bergundy** [comment]
I'm not convinced this is desired though.
Shutdown ATM is a synchronous operation that only requests shutdown, making it return the run promise is a bit confusing especially because the stack trace would be weird.

**Comment by bergundy** [comment]
As discussed in slack I'm closing this issue.
