### ISSUE TITLE
Include a roadmap in readme

### ISSUE THREAD

**Issue by pikaciu22x** [temporalio/sdk-node#39]
Hey everyone,

I'm excited to see, that you are willing to create a node client! Sorry for creating this as an issue in case i did it in the wrong place. I just wanted to ask whether adding a roadmap would be possible? For example, https://github.com/firdaus/cadence-python lists supported features, etc. This would really help to grasp in what state is the current project.

My companies development team wants to start using temporal, but currently, the vast majority of our codebase consists of typescript or python, thus creating a barrier. I would love to contribute to help this project.

**Comment by sw-yx** [comment]
hi, thanks for filing this, we aren't soliciting contributions yet as this project is still in very early stages, however you can try it out now per the README and give feedback if anything doesn't work. thank you!

**Comment by bergundy** [comment]
We're working on having a functional alpha release in the upcoming weeks, hopefully in a week or 2 from now.
The release will include running activities and workflows and a basic service client.
We won't have advanced features like local activities, side effects, and interceptors yet but it should be enough to start working with the client.

We're currently missing:
- Ease of installation (the package relies on 3 different native modules written in c++ and rust). 
- Documentation
- Integration tests for running activities

**Comment by bergundy** [comment]
Added an alpha milestone

**Comment by bergundy** [comment]
@pikaciu22x I'm closing this, feel free to re-open if you want to continue the discussion.
