### ISSUE TITLE
[Feature Request] Use `@grpc/grpc-js` instead of the deprecated `grpc` package

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#59]
It's implemented in pure JS which should make installations on node 15 faster. 
See:
https://www.npmjs.com/package/@grpc/grpc-js
https://www.npmjs.com/package/grpc

**Comment by sw-yx** [comment]
just so you know we recently had to go the other way in Temporal web bc of a TLS Issue @feedmeapples

**Comment by bergundy** [comment]
That's unfortunate, I hope this is solved soon.
Can you please link the issue here @sw-yx?

**Comment by feedmeapples** [comment]
@bergundy  they added separate env variables to allow users solving TLS inconsistency issues https://github.com/grpc/grpc-node/issues/804

I couldn't repro the same issue locally (mtls worked fine with simple tls setup), though did see a repro with few other reported servers https://github.com/temporalio/web/pull/301

cc @sw-yx
