### ISSUE TITLE
[Feature Request] Support workflow versioning

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-node#68]
Other SDKs support workflow versioning in order to support code changes for running workflows.
We must add this functionality to the Node SDK too shortly after the alpha.
Some possible solutions would be:
1. Do what we do in [Java](https://docs.temporal.io/docs/java-versioning) and record a marker in the WF history.
2. Bundle workflows with their dependencies using a bundler such as [webpack](https://webpack.js.org/) and include all workflow relevant versions in the worker's workflows directory.
3. Keep using modules and add versioning capabilities to the loader (requires a way to store loaded modules).

**Comment by Sushisource** [comment]
See https://github.com/temporalio/sdk-core/pull/156
